---
book_repo: pivotal-cf/docs-book-pas-windows
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-pcf-windows
    ref: 'master'
    at_path: 'docs-content'
  directory: runtimes/windows/2-1
  subnav_template: windows_subnav_2-1.erb
  product_info:
    use_local_header: true
    latest_stable_version: "v2.0"
    local_header_img: /images/cloud_rings.png
    local_header_title: PAS for Windows
    search_placeholder: "Search PAS for Windows v2.1"
    url_prefix: runtimes/windows/2-1
    local_product_version: "2.1"
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/runtimes/windows/2-0
        display_name: v2.0

book_title: PAS for Windows
